name       : xml-security-c
version    : 2.0.2
release    : 4
source     :
    - http://www.apache.org/dist/santuario/c-library/xml-security-c-2.0.2.tar.bz2 : 39e963ab4da477b7bda058f06db37228664c68fe68902d86e334614dd06e046b
license    : Apache-2.0
component  : programming
summary    : Apache XML Security for C++ - This library includes a mature Digital Signature and Encryption implementation
description: |
    Apache XML Security for C++ - This library includes a mature Digital Signature and Encryption implementation
builddeps  :
    - pkgconfig(openssl)
    - pkgconfig(xerces-c)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
